services:
  supabase:
    image: supabase/supabase-local
    ports:
      - "54323:54323"  # Supabase Studio
      - "54321:54321"  # API
      - "54322:54322"  # Database
    environment:
      POSTGRES_PASSWORD: postgres
      JWT_SECRET: your-super-secret-jwt-token

  hardhat:
    image: node:18
    working_dir: /app
    volumes:
      - ../contracts:/app
    ports:
      - "8545:8545"
    command: npx hardhat node